export const DaftarAgenda = [
    {
        date: new Date(2021, 7, 2),
        desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer a eros neque. Proin leo elit, lacinia et congue vitae, lacinia eget lectus. Fusce a justo quam. Vivamus laoreet enim vitae quam luctus, non aliquam nunc pellentesque. Integer vestibulum et purus at ultricies. Proin ultrices ipsum nec pulvinar viverra. Nunc congue sollicitudin ante, a aliquet ligula mollis vitae.',
        title: 'Pembukaan & PPSMB Universitas Hari Pertama',
        linkElok: 'https://elok.ugm.ac.id/course/index.php?categoryid=52',
        linkLengkap: 'https://ppsmb.ugm.ac.id/2021/agenda',
        linkTugas: 'https://simpan.ugm.ac.id/s/CBN21EkVVmugT9C#pdfviewer',
        linkSimaster: 'https://simaster.ugm.ac.id/kemahasiswaan/ppsmb/',
    },
    {
        date: new Date(2021, 7, 3),
        title: 'PPSMB Universitas Hari Kedua',
        desc: 'Pada hari kedua, blablabla.',
        linkElok: 'https://elok.ugm.ac.id/course/index.php?categoryid=52',
        linkLengkap: 'https://ppsmb.ugm.ac.id/2021/agenda',
        linkTugas: 'https://simpan.ugm.ac.id/s/CBN21EkVVmugT9C#pdfviewer',
        linkSimaster: 'https://simaster.ugm.ac.id/kemahasiswaan/ppsmb/',
    },
    {
        date: new Date(2021, 7, 4),
        title: 'PPSMB Fakultas Hari Pertama',
        desc: 'Pada hari ketiga, blablabla.',
        linkElok: 'https://elok.ugm.ac.id/course/index.php?categoryid=52',
        linkLengkap: 'https://ppsmb.ugm.ac.id/2021/agenda',
        linkTugas: 'https://simpan.ugm.ac.id/s/CBN21EkVVmugT9C#pdfviewer',
        linkSimaster: 'https://simaster.ugm.ac.id/kemahasiswaan/ppsmb/',
    },
    {
        date: new Date(2021, 7, 5),
        title: 'PPSMB Fakultas Hari Kedua',
        desc: 'Pada hari keempat, blablabla.',
        linkElok: 'https://elok.ugm.ac.id/course/index.php?categoryid=52',
        linkLengkap: 'https://ppsmb.ugm.ac.id/2021/agenda',
        linkTugas: 'https://simpan.ugm.ac.id/s/CBN21EkVVmugT9C#pdfviewer',
        linkSimaster: 'https://simaster.ugm.ac.id/kemahasiswaan/ppsmb/',
    },
    {
        date: new Date(2021, 7, 6),
        title: 'PPSMB Soft Skills Hari Pertama',
        desc: 'Pada hari kelima, blablabla.',
        linkElok: 'https://elok.ugm.ac.id/course/index.php?categoryid=52',
        linkLengkap: 'https://ppsmb.ugm.ac.id/2021/agenda',
        linkTugas: 'https://simpan.ugm.ac.id/s/CBN21EkVVmugT9C#pdfviewer',
        linkSimaster: 'https://simaster.ugm.ac.id/kemahasiswaan/ppsmb/',
    },
    {
        date: new Date(2021, 7, 7),
        title: 'PPSMB Soft Skills Hari Kedua',
        desc: 'Pada hari keenam, blablabla.',
        linkElok: 'https://elok.ugm.ac.id/course/index.php?categoryid=52',
        linkLengkap: 'https://ppsmb.ugm.ac.id/2021/agenda',
        linkTugas: 'https://simpan.ugm.ac.id/s/CBN21EkVVmugT9C#pdfviewer',
        linkSimaster: 'https://simaster.ugm.ac.id/kemahasiswaan/ppsmb/',
    },
    {
        date: new Date(2021, 7, 8),
        title: 'Action Plan',
        desc: 'Pada penerapan action plan, blablabla.',
        linkElok: 'https://elok.ugm.ac.id/course/index.php?categoryid=52',
        linkLengkap: 'https://ppsmb.ugm.ac.id/2021/agenda',
        linkTugas: 'https://simpan.ugm.ac.id/s/CBN21EkVVmugT9C#pdfviewer',
        linkSimaster: 'https://simaster.ugm.ac.id/kemahasiswaan/ppsmb/',
    },
    {
        date: new Date(2021, 7, 8),
        title: 'Action Plan',
        desc: 'Pada penerapan action plan, blablabla.',
        linkElok: 'https://elok.ugm.ac.id/course/index.php?categoryid=52',
        linkLengkap: 'https://ppsmb.ugm.ac.id/2021/agenda',
        linkTugas: 'https://simpan.ugm.ac.id/s/CBN21EkVVmugT9C#pdfviewer',
        linkSimaster: 'https://simaster.ugm.ac.id/kemahasiswaan/ppsmb/',
    },
    {
        date: new Date(2021, 7, 9),
        title: 'Action Plan',
        desc: 'Pada penerapan action plan, blablabla.',
        linkElok: 'https://elok.ugm.ac.id/course/index.php?categoryid=52',
        linkLengkap: 'https://ppsmb.ugm.ac.id/2021/agenda',
        linkTugas: 'https://simpan.ugm.ac.id/s/CBN21EkVVmugT9C#pdfviewer',
        linkSimaster: 'https://simaster.ugm.ac.id/kemahasiswaan/ppsmb/',
    },
    {
        date: new Date(2021, 7, 10),
        title: 'Action Plan',
        desc: 'Pada penerapan action plan, blablabla.',
        linkElok: 'https://elok.ugm.ac.id/course/index.php?categoryid=52',
        linkLengkap: 'https://ppsmb.ugm.ac.id/2021/agenda',
        linkTugas: 'https://simpan.ugm.ac.id/s/CBN21EkVVmugT9C#pdfviewer',
        linkSimaster: 'https://simaster.ugm.ac.id/kemahasiswaan/ppsmb/',
    },
    {
        date: new Date(2021, 7, 14),
        title: 'Penutupan',
        desc: 'Pada penerapan penutupan, blablabla.',
        linkElok: 'https://elok.ugm.ac.id/course/index.php?categoryid=52',
        linkLengkap: 'https://ppsmb.ugm.ac.id/2021/agenda',
        linkTugas: 'https://simpan.ugm.ac.id/s/CBN21EkVVmugT9C#pdfviewer',
        linkSimaster: 'https://simaster.ugm.ac.id/kemahasiswaan/ppsmb/',
    },
]