/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/Logo-transformed.glb");

  async function handleHover(e) {
    document.body.style.cursor = "pointer";
  }

  async function clearHover(e) {
    document.body.style.cursor = "auto";
  }

  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name="Scene"
        onClick={props.setModalActionPlan}
        onPointerOver={(e) => handleHover(e)}
        onPointerOut={(e) => clearHover(e)}
      >
        <group
          name="Logo_Palapa"
          rotation={[Math.PI / 2, 0, 0]}
          scale={81.25658}
        >
          <mesh
            name="Curve014"
            geometry={nodes.Curve014.geometry}
            material={materials["Rod.Red"]}
          />
          <mesh
            name="Curve014_1"
            geometry={nodes.Curve014_1.geometry}
            material={materials.Yellow}
          />
          <mesh
            name="Curve014_2"
            geometry={nodes.Curve014_2.geometry}
            material={materials.Green}
          />
          <mesh
            name="Curve014_3"
            geometry={nodes.Curve014_3.geometry}
            material={materials.Orange}
          />
          <mesh
            name="Curve014_4"
            geometry={nodes.Curve014_4.geometry}
            material={materials.Purple}
          />
          <mesh
            name="Curve014_5"
            geometry={nodes.Curve014_5.geometry}
            material={materials.Blue}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Logo-transformed.glb");
