export const srlPhotos = [{
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/1.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/1.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/21.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/21.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/3.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/3.webp"}`,
        alt: "",
        width: 9,
        height: 16,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/4.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/4.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/5.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/5.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/6.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/6.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/2.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/2.webp"}`,
        alt: "",
        width: 9,
        height: 16,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/7.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/7.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/8.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/8.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/9.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/9.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/11.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/11.webp"}`,
        alt: "",
        width: 9,
        height: 16,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/12.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/12.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/10.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/10.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/13.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/13.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/14.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/14.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/20.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/20.webp"}`,
        alt: "",
        width: 9,
        height: 16,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/15.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/15.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/16.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/16.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/17.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/17.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/18.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/18.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/19.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/19.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/21.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/21.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/22.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/22.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/23.jpg"}`,
        thumbnail: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/23.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
]

export const srcPhotos = [{
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/1.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/1.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/21.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/21.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/3.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/3.webp"}`,
        alt: "",
        width: 9,
        height: 16,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/4.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/4.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/5.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/5.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/6.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/6.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/2.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/2.webp"}`,
        alt: "",
        width: 9,
        height: 16,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/7.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/7.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/8.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/8.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/9.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/9.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/11.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/11.webp"}`,
        alt: "",
        width: 9,
        height: 16,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/12.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/12.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/10.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/10.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/13.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/13.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/14.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/14.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/20.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/20.webp"}`,
        alt: "",
        width: 9,
        height: 16,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/15.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/15.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/16.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/16.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/17.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/17.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/18.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/18.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/19.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/19.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/22.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/22.webp"}`,
        alt: "",
        width: 3,
        height: 2,
    },
    {
        fwSrc: `${process.env.PUBLIC_URL + "/assets/img/galeri/full-width/23.jpg"}`,
        src: `${process.env.PUBLIC_URL + "/assets/img/galeri/thumbnail/23.webp"}`,
        alt: "",
        width: 16,
        height: 9,
    },
]