/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useState, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useTexture, Html } from "@react-three/drei";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/model.glb");
  const [object, setObject] = useState();

  let start = 0,
    end = 0,
    last = 0;

  async function startCount(e) {
    start = Date.now();
  }

  async function endCount(e) {
    end = Date.now();
    if (end - start < 200 && end - last > 1000) {
      handleClick(e);
      last = Date.now();
    }
  }

  async function handleClick(e) {
    props.showModal({
      position: {
        x: e.object.parent.position.x,
        y: e.object.parent.position.y,
        z: e.object.parent.position.z,
      },
      name: e.object.parent.name,
    });
  }

  async function handleHover(e) {
    setObject({
      position: {
        x: e.object.parent.position.x,
        z: e.object.parent.position.z,
      },
      name: e.object.parent.name,
    });
    document.body.style.cursor = "pointer";
  }

  async function clearHover(e) {
    setObject(null);
    document.body.style.cursor = "auto";
  }

  return (
    <>
      <SpriteHover object={object} setObject={setObject} />
      <group
        ref={group}
        {...props}
        dispose={null}
        onPointerDown={(e) => startCount(e)}
        onPointerUp={(e) => endCount(e)}
        // onPointerOver={(e) => handleHover(e)}
        // onPointerOut={(e) => clearHover(e)}
      >
        <group name="Scene">
          <group
            name="Camera"
            position={[-58.57154, 11.56955, 63.13383]}
            rotation={[1.49531, -0.08241, 0.82766]}
          />
          <group name="Point" position={[141.88148, -108.0954, -30.31798]} />
          <group
            name="Point001"
            position={[-178.31555, -85.85108, -30.31798]}
          />
          <group
            name="Point002"
            position={[-18.71292, -85.85108, -170.36694]}
          />
          <group name="Point003" position={[42.20517, -148.08733, 155.25099]} />
          <group
            name="Sun"
            position={[54.39194, 53.91137, 34.38828]}
            rotation={[-2.98306, -0.28452, -2.81722]}
          />
          <group
            name="Island"
            position={[-149.18214, -93.6482, 41.89563]}
            rotation={[Math.PI, -1.29678, Math.PI]}
            scale={[35.02587, 35.02586, 35.02587]}
          >
            <mesh
              name="Icosphere007"
              geometry={nodes.Icosphere007.geometry}
              material={nodes.Icosphere007.material}
            />
            <mesh
              name="Icosphere007_1"
              geometry={nodes.Icosphere007_1.geometry}
              material={materials.Island_Rock}
            />
            <mesh
              name="Icosphere007_2"
              geometry={nodes.Icosphere007_2.geometry}
              material={materials.Island_Grass}
            />
            <mesh
              name="Icosphere007_3"
              geometry={nodes.Icosphere007_3.geometry}
              material={nodes.Icosphere007_3.material}
            />
            <mesh
              name="Icosphere007_4"
              geometry={nodes.Icosphere007_4.geometry}
              material={materials.Island_Snow}
            />
            <mesh
              name="Icosphere007_5"
              geometry={nodes.Icosphere007_5.geometry}
              material={materials.Island_Moss}
            />
          </group>
          <mesh
            name="Land"
            geometry={nodes.Land.geometry}
            material={materials.Land_Grass}
            position={[17.04576, 0.04594, -10.06862]}
            rotation={[0, -0.00697, 0]}
            scale={[184.55013, 184.55013, 184.55013]}
          />
          <mesh
            name="River"
            geometry={nodes.River.geometry}
            material={materials["River.001"]}
            position={[13.23225, -1.4548, -9.06602]}
            scale={[184.55013, 184.55013, 184.55013]}
          />
          <group
            name="Rock"
            position={[-143.59546, -78.67705, 51.18751]}
            rotation={[Math.PI / 2, 0, 0.54376]}
            scale={[24.01039, 24.01039, 24.01037]}
          >
            <mesh
              name="Rock_2_Cube013"
              geometry={nodes.Rock_2_Cube013.geometry}
              material={materials["Rock.042"]}
            />
            <mesh
              name="Rock_2_Cube013_1"
              geometry={nodes.Rock_2_Cube013_1.geometry}
              material={materials["Rock.036"]}
            />
            <mesh
              name="Rock_2_Cube013_2"
              geometry={nodes.Rock_2_Cube013_2.geometry}
              material={materials["Rock.039"]}
            />
            <mesh
              name="Rock_2_Cube013_3"
              geometry={nodes.Rock_2_Cube013_3.geometry}
              material={materials["Rock.037"]}
            />
            <mesh
              name="Rock_2_Cube013_4"
              geometry={nodes.Rock_2_Cube013_4.geometry}
              material={materials["Rock.038"]}
            />
          </group>
          <group
            name="Ship"
            position={[121.23643, -1.33839, 35.43839]}
            rotation={[Math.PI / 2, 0, 0.4622]}
            scale={[7.2399, 7.2399, 8.10905]}
          >
            <mesh
              name="Sail_Cube001"
              geometry={nodes.Sail_Cube001.geometry}
              material={materials["DarkWood.001"]}
            />
            <mesh
              name="Sail_Cube001_1"
              geometry={nodes.Sail_Cube001_1.geometry}
              material={materials["Sail.001"]}
            />
            <mesh
              name="Sail_Cube001_2"
              geometry={nodes.Sail_Cube001_2.geometry}
              material={materials["LightWood.002"]}
            />
            <mesh
              name="Sail_Cube001_3"
              geometry={nodes.Sail_Cube001_3.geometry}
              material={materials["Steel.001"]}
            />
            <mesh
              name="Sail_Cube001_4"
              geometry={nodes.Sail_Cube001_4.geometry}
              material={materials["DarkWood.003"]}
            />
            <mesh
              name="Sail_Cube001_5"
              geometry={nodes.Sail_Cube001_5.geometry}
              material={materials["Sail.003"]}
            />
            <mesh
              name="Sail_Cube001_6"
              geometry={nodes.Sail_Cube001_6.geometry}
              material={materials["LightWood.005"]}
            />
            <mesh
              name="Sail_Cube001_7"
              geometry={nodes.Sail_Cube001_7.geometry}
              material={materials["Steel.003"]}
            />
            <mesh
              name="Sail_Cube001_8"
              geometry={nodes.Sail_Cube001_8.geometry}
              material={materials["DarkWood.002"]}
            />
            <mesh
              name="Sail_Cube001_9"
              geometry={nodes.Sail_Cube001_9.geometry}
              material={materials["Sail.002"]}
            />
            <mesh
              name="Sail_Cube001_10"
              geometry={nodes.Sail_Cube001_10.geometry}
              material={materials["LightWood.004"]}
            />
            <mesh
              name="Sail_Cube001_11"
              geometry={nodes.Sail_Cube001_11.geometry}
              material={materials["Steel.002"]}
            />
          </group>
          <group
            name="Tree"
            position={[-160.76155, -84.15355, 52.84361]}
            rotation={[Math.PI / 2, 0, -0.8474]}
            scale={[7.08703, 7.08703, 7.08703]}
          >
            <mesh
              name="Willow_4_Cube018"
              geometry={nodes.Willow_4_Cube018.geometry}
              material={materials["Wood.138"]}
            />
            <mesh
              name="Willow_4_Cube018_1"
              geometry={nodes.Willow_4_Cube018_1.geometry}
              material={materials["DarkGreen.100"]}
            />
            <mesh
              name="Willow_4_Cube018_2"
              geometry={nodes.Willow_4_Cube018_2.geometry}
              material={materials["White.028"]}
            />
          </group>
          <mesh
            name="Road"
            geometry={nodes.Road.geometry}
            material={materials["Road.001"]}
            position={[52.75742, -0.02115, 54.64096]}
            rotation={[Math.PI / 2, 0, -0.28041]}
            scale={[0.13929, 0.13929, 0.13929]}
          />
          <mesh
            name="Asrama_Mahasiswa_Mlati"
            geometry={nodes.Asrama_Mahasiswa_Mlati.geometry}
            material={nodes.Asrama_Mahasiswa_Mlati.material}
            position={[-81.05164, 0.5595, -73.87828]}
            rotation={[0, 0.68219, 0]}
            scale={[3.94237, 3.94237, 3.94237]}
          />
          <group
            name="Balairung"
            position={[-3.82544, 0.21692, -41.05731]}
            rotation={[Math.PI / 2, 0, 1.60896]}
            scale={[0.07372, 0.07372, 0.07372]}
          >
            <mesh
              name="Balairung001"
              geometry={nodes.Balairung001.geometry}
              material={nodes.Balairung001.material}
            />
            <mesh
              name="Balairung001_1"
              geometry={nodes.Balairung001_1.geometry}
              material={materials.Balairung_Black}
            />
            <mesh
              name="Balairung001_2"
              geometry={nodes.Balairung001_2.geometry}
              material={materials.Balairung_FireBrick}
            />
            <mesh
              name="Balairung001_3"
              geometry={nodes.Balairung001_3.geometry}
              material={materials.Balairung_Body}
            />
            <mesh
              name="Balairung001_4"
              geometry={nodes.Balairung001_4.geometry}
              material={materials.Balairung_LightGray}
            />
            <mesh
              name="Balairung001_5"
              geometry={nodes.Balairung001_5.geometry}
              material={materials.Balairung_Sienna}
            />
            <mesh
              name="Balairung001_6"
              geometry={nodes.Balairung001_6.geometry}
              material={materials.Balairung_LightBlue}
            />
            <mesh
              name="Balairung001_7"
              geometry={nodes.Balairung001_7.geometry}
              material={nodes.Balairung001_7.material}
            />
            <mesh
              name="Balairung001_8"
              geometry={nodes.Balairung001_8.geometry}
              material={materials.Balairung_Crimson}
            />
            <mesh
              name="Balairung001_9"
              geometry={nodes.Balairung001_9.geometry}
              material={materials.Balairung_Grey}
            />
            <mesh
              name="Balairung001_10"
              geometry={nodes.Balairung001_10.geometry}
              material={materials.Balairung_Glass_1}
            />
            <mesh
              name="Balairung001_11"
              geometry={nodes.Balairung001_11.geometry}
              material={materials.Balairung_Glass_2}
            />
            <mesh
              name="Balairung001_12"
              geometry={nodes.Balairung001_12.geometry}
              material={materials.Balairung_Wood}
            />
            <mesh
              name="Balairung001_13"
              geometry={nodes.Balairung001_13.geometry}
              material={materials.Balairung_Grass}
            />
            <mesh
              name="Balairung001_14"
              geometry={nodes.Balairung001_14.geometry}
              material={materials.Balairung_Golden}
            />
          </group>
          <group
            name="Fakulas_Kedokteran_Gigi"
            position={[-64.64047, 0.20852, 3.28671]}
            rotation={[Math.PI / 2, 0, -3.07889]}
            scale={[0.00041, 0.00041, 0.00041]}
          >
            <mesh
              name="Fakulas_Kedokteran_Gigi001"
              geometry={nodes.Fakulas_Kedokteran_Gigi001.geometry}
              material={materials.FKG_Tulisan}
            />
            <mesh
              name="Fakulas_Kedokteran_Gigi001_1"
              geometry={nodes.Fakulas_Kedokteran_Gigi001_1.geometry}
              material={materials.FKG_Body}
            />
            <mesh
              name="Fakulas_Kedokteran_Gigi001_2"
              geometry={nodes.Fakulas_Kedokteran_Gigi001_2.geometry}
              material={materials.FKG_DarkGray}
            />
            <mesh
              name="Fakulas_Kedokteran_Gigi001_3"
              geometry={nodes.Fakulas_Kedokteran_Gigi001_3.geometry}
              material={materials.FKG_LightBlue}
            />
            <mesh
              name="Fakulas_Kedokteran_Gigi001_4"
              geometry={nodes.Fakulas_Kedokteran_Gigi001_4.geometry}
              material={materials.FKG_FireBrick}
            />
          </group>
          <group
            name="Fakultas_Biologi"
            position={[-37.39935, 0.20852, -54.89989]}
            rotation={[Math.PI / 2, 0, -1.5775]}
            scale={[0.22115, 0.22115, 0.22115]}
          >
            <mesh
              name="BIOLOGI_UGM001"
              geometry={nodes.BIOLOGI_UGM001.geometry}
              material={materials.Biologi_Tulisan}
            />
            <mesh
              name="BIOLOGI_UGM001_1"
              geometry={nodes.BIOLOGI_UGM001_1.geometry}
              material={materials.Biologi_Body}
            />
            <mesh
              name="BIOLOGI_UGM001_2"
              geometry={nodes.BIOLOGI_UGM001_2.geometry}
              material={materials.Biologi_Accent}
            />
            <mesh
              name="BIOLOGI_UGM001_3"
              geometry={nodes.BIOLOGI_UGM001_3.geometry}
              material={materials.Biologi_Jendela}
            />
            <mesh
              name="BIOLOGI_UGM001_4"
              geometry={nodes.BIOLOGI_UGM001_4.geometry}
              material={materials.Biologi_Foundation}
            />
            <mesh
              name="BIOLOGI_UGM001_5"
              geometry={nodes.BIOLOGI_UGM001_5.geometry}
              material={materials.Biologi_FireBrick}
            />
          </group>
          <group
            name="Fakultas_Ekonomika_dan_Bisnis"
            position={[15.74105, 0.25236, -12.62922]}
            rotation={[Math.PI / 2, 0, 1.57964]}
            scale={[0.24814, 0.24814, 0.24814]}
          >
            <mesh
              name="Fakultas_Ekonomika_dan_Bisnis001"
              geometry={nodes.Fakultas_Ekonomika_dan_Bisnis001.geometry}
              material={materials.FrontColor}
            />
            <mesh
              name="Fakultas_Ekonomika_dan_Bisnis001_1"
              geometry={nodes.Fakultas_Ekonomika_dan_Bisnis001_1.geometry}
              material={materials.Translucent_Glass_Blue}
            />
            <mesh
              name="Fakultas_Ekonomika_dan_Bisnis001_2"
              geometry={nodes.Fakultas_Ekonomika_dan_Bisnis001_2.geometry}
              material={materials.Tower}
            />
            <mesh
              name="Fakultas_Ekonomika_dan_Bisnis001_3"
              geometry={nodes.Fakultas_Ekonomika_dan_Bisnis001_3.geometry}
              material={materials["Wall Grey"]}
            />
          </group>
          <group
            name="Fakultas_Farmasi"
            position={[-24.22468, 0.34509, -9.40797]}
            rotation={[Math.PI / 2, 0, 0.10953]}
            scale={[0.01383, 0.01383, 0.01383]}
          >
            <mesh
              name="Fakultas_Farmasi001"
              geometry={nodes.Fakultas_Farmasi001.geometry}
              material={materials.Farmasi_White}
            />
            <mesh
              name="Fakultas_Farmasi001_1"
              geometry={nodes.Fakultas_Farmasi001_1.geometry}
              material={materials.Farmasi_Body}
            />
            <mesh
              name="Fakultas_Farmasi001_2"
              geometry={nodes.Fakultas_Farmasi001_2.geometry}
              material={materials.Farmasi_Grey}
            />
            <mesh
              name="Fakultas_Farmasi001_3"
              geometry={nodes.Fakultas_Farmasi001_3.geometry}
              material={materials.Farmasi_Metal}
            />
            <mesh
              name="Fakultas_Farmasi001_4"
              geometry={nodes.Fakultas_Farmasi001_4.geometry}
              material={materials.Farmasi_Gold}
            />
            <mesh
              name="Fakultas_Farmasi001_5"
              geometry={nodes.Fakultas_Farmasi001_5.geometry}
              material={materials.Farmasi_Wall}
            />
            <mesh
              name="Fakultas_Farmasi001_6"
              geometry={nodes.Fakultas_Farmasi001_6.geometry}
              material={materials.Farmasi_DarkGray}
            />
            <mesh
              name="Fakultas_Farmasi001_7"
              geometry={nodes.Fakultas_Farmasi001_7.geometry}
              material={materials.Farmasi_FireBrick}
            />
            <mesh
              name="Fakultas_Farmasi001_8"
              geometry={nodes.Fakultas_Farmasi001_8.geometry}
              material={materials.Farmasi_Brown}
            />
            <mesh
              name="Fakultas_Farmasi001_9"
              geometry={nodes.Fakultas_Farmasi001_9.geometry}
              material={materials.Farmasi_Glass_1}
            />
            <mesh
              name="Fakultas_Farmasi001_10"
              geometry={nodes.Fakultas_Farmasi001_10.geometry}
              material={materials.Farmasi_Glass_2}
            />
            <mesh
              name="Fakultas_Farmasi001_11"
              geometry={nodes.Fakultas_Farmasi001_11.geometry}
              material={materials.Farmasi_Glass_3}
            />
          </group>
          <group
            name="Fakultas_Filsafat"
            position={[34.01514, 0.40873, 9.89052]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.01332, 0.01332, 0.01332]}
          >
            <mesh
              name="filsafat_(2)001"
              geometry={nodes["filsafat_(2)001"].geometry}
              material={materials.Filsafat_Body}
            />
            <mesh
              name="filsafat_(2)001_1"
              geometry={nodes["filsafat_(2)001_1"].geometry}
              material={materials.FIlsafat_Translucent}
            />
            <mesh
              name="filsafat_(2)001_2"
              geometry={nodes["filsafat_(2)001_2"].geometry}
              material={materials.Filsafat_FireBrick}
            />
            <mesh
              name="filsafat_(2)001_3"
              geometry={nodes["filsafat_(2)001_3"].geometry}
              material={materials.Filsafat_Jendela}
            />
          </group>
          <group
            name="Fakultas_Geografi"
            position={[-26.8091, 0.93755, -75.0618]}
            rotation={[Math.PI / 2, 0, 1.64065]}
            scale={[2.15347, 2.15347, 2.15347]}
          >
            <mesh
              name="Fakultas_Geografi001"
              geometry={nodes.Fakultas_Geografi001.geometry}
              material={materials.Geo_Gold}
            />
            <mesh
              name="Fakultas_Geografi001_1"
              geometry={nodes.Fakultas_Geografi001_1.geometry}
              material={materials.Geo_Body}
            />
            <mesh
              name="Fakultas_Geografi001_2"
              geometry={nodes.Fakultas_Geografi001_2.geometry}
              material={materials.Geo_DarkGray}
            />
            <mesh
              name="Fakultas_Geografi001_3"
              geometry={nodes.Fakultas_Geografi001_3.geometry}
              material={materials.Geo_Black}
            />
            <mesh
              name="Fakultas_Geografi001_4"
              geometry={nodes.Fakultas_Geografi001_4.geometry}
              material={materials.Geo_Gray}
            />
            <mesh
              name="Fakultas_Geografi001_5"
              geometry={nodes.Fakultas_Geografi001_5.geometry}
              material={materials.Geo_FireBrick}
            />
          </group>
          <group
            name="Fakultas_Hukum"
            position={[51.05442, 0.49984, -7.35406]}
            rotation={[Math.PI / 2, 0, -1.54283]}
            scale={[0.7713, 0.7713, 0.7713]}
          >
            <mesh
              name="Fakultas_Hukum001"
              geometry={nodes.Fakultas_Hukum001.geometry}
              material={materials.Hukum_Accent}
            />
            <mesh
              name="Fakultas_Hukum001_1"
              geometry={nodes.Fakultas_Hukum001_1.geometry}
              material={materials.Hukum_Front}
            />
            <mesh
              name="Fakultas_Hukum001_2"
              geometry={nodes.Fakultas_Hukum001_2.geometry}
              material={materials.Hukum_DarkGray}
            />
            <mesh
              name="Fakultas_Hukum001_3"
              geometry={nodes.Fakultas_Hukum001_3.geometry}
              material={materials.Hukum_FireBrick}
            />
            <mesh
              name="Fakultas_Hukum001_4"
              geometry={nodes.Fakultas_Hukum001_4.geometry}
              material={materials.Hukum_Sienna}
            />
          </group>
          <group
            name="Fakultas_Ilmu_dan_Budaya"
            position={[13.61717, 0.20857, 10.18011]}
            rotation={[Math.PI / 2, 0, 1.59269]}
            scale={[0.14182, 0.14182, 0.14182]}
          >
            <mesh
              name="Fakultas_Ilmu_dan_Budaya001"
              geometry={nodes.Fakultas_Ilmu_dan_Budaya001.geometry}
              material={materials.FIB_Body}
            />
            <mesh
              name="Fakultas_Ilmu_dan_Budaya001_1"
              geometry={nodes.Fakultas_Ilmu_dan_Budaya001_1.geometry}
              material={materials.FIB_DarkGray}
            />
            <mesh
              name="Fakultas_Ilmu_dan_Budaya001_2"
              geometry={nodes.Fakultas_Ilmu_dan_Budaya001_2.geometry}
              material={materials.FIB_LightBlue}
            />
            <mesh
              name="Fakultas_Ilmu_dan_Budaya001_3"
              geometry={nodes.Fakultas_Ilmu_dan_Budaya001_3.geometry}
              material={materials.FIB_Brick}
            />
          </group>
          <group
            name="Fakultas_Ilmu_Sosial_dan_Politik"
            position={[11.08782, 1.56322, -21.30253]}
            rotation={[1.56989, -0.01813, 1.59044]}
            scale={[0.02162, 0.02162, 0.02162]}
          >
            <mesh
              name="Fakultas_Ilmu_Sosial_dan_Politik001"
              geometry={nodes.Fakultas_Ilmu_Sosial_dan_Politik001.geometry}
              material={materials.Fisipol_Body}
            />
            <mesh
              name="Fakultas_Ilmu_Sosial_dan_Politik001_1"
              geometry={nodes.Fakultas_Ilmu_Sosial_dan_Politik001_1.geometry}
              material={materials.Fisipol_FireBrick}
            />
            <mesh
              name="Fakultas_Ilmu_Sosial_dan_Politik001_2"
              geometry={nodes.Fakultas_Ilmu_Sosial_dan_Politik001_2.geometry}
              material={materials.Fisipol_DarkGray}
            />
          </group>
          <group
            name="Fakultas_Kedokteran,_Kesehatan_Masyarakat_,dan_Keperawatan"
            position={[-45.29216, 0.25029, 4.0763]}
            rotation={[Math.PI / 2, 0, -1.52533]}
            scale={[0.11081, 0.11081, 0.11081]}
          >
            <mesh
              name="Fakultas_Kedokteran,_Kesehatan_Masyarakat_,dan_Keperawatan001"
              geometry={
                nodes[
                  "Fakultas_Kedokteran,_Kesehatan_Masyarakat_,dan_Keperawatan001"
                ].geometry
              }
              material={materials.FKKMK_Body}
            />
            <mesh
              name="Fakultas_Kedokteran,_Kesehatan_Masyarakat_,dan_Keperawatan001_1"
              geometry={
                nodes[
                  "Fakultas_Kedokteran,_Kesehatan_Masyarakat_,dan_Keperawatan001_1"
                ].geometry
              }
              material={materials.FKKMK_Gray}
            />
            <mesh
              name="Fakultas_Kedokteran,_Kesehatan_Masyarakat_,dan_Keperawatan001_2"
              geometry={
                nodes[
                  "Fakultas_Kedokteran,_Kesehatan_Masyarakat_,dan_Keperawatan001_2"
                ].geometry
              }
              material={materials.FKKMK_PaleGolden}
            />
            <mesh
              name="Fakultas_Kedokteran,_Kesehatan_Masyarakat_,dan_Keperawatan001_3"
              geometry={
                nodes[
                  "Fakultas_Kedokteran,_Kesehatan_Masyarakat_,dan_Keperawatan001_3"
                ].geometry
              }
              material={materials.FKKMK_Glass}
            />
            <mesh
              name="Fakultas_Kedokteran,_Kesehatan_Masyarakat_,dan_Keperawatan001_4"
              geometry={
                nodes[
                  "Fakultas_Kedokteran,_Kesehatan_Masyarakat_,dan_Keperawatan001_4"
                ].geometry
              }
              material={materials.FKKMK_DarkGray}
            />
          </group>
          <group
            name="Fakultas_Kedokteran_Hewan"
            position={[60.38102, 0.20852, -63.74555]}
            rotation={[Math.PI / 2, 0, -0.13505]}
            scale={[0.47043, 0.47043, 0.47043]}
          >
            <mesh
              name="Fakultas_Kedokteran_Hewan001"
              geometry={nodes.Fakultas_Kedokteran_Hewan001.geometry}
              material={materials.FKH_Body}
            />
            <mesh
              name="Fakultas_Kedokteran_Hewan001_1"
              geometry={nodes.Fakultas_Kedokteran_Hewan001_1.geometry}
              material={materials.FKH_Crimson}
            />
            <mesh
              name="Fakultas_Kedokteran_Hewan001_2"
              geometry={nodes.Fakultas_Kedokteran_Hewan001_2.geometry}
              material={materials.FKH_Black}
            />
            <mesh
              name="Fakultas_Kedokteran_Hewan001_3"
              geometry={nodes.Fakultas_Kedokteran_Hewan001_3.geometry}
              material={materials.FKH_DarkGray}
            />
            <mesh
              name="Fakultas_Kedokteran_Hewan001_4"
              geometry={nodes.Fakultas_Kedokteran_Hewan001_4.geometry}
              material={materials.FKH_Golden}
            />
            <mesh
              name="Fakultas_Kedokteran_Hewan001_5"
              geometry={nodes.Fakultas_Kedokteran_Hewan001_5.geometry}
              material={materials.FKH_FireBrick}
            />
          </group>
          <group
            name="Fakultas_Kehutanan"
            position={[29.47341, 4.91385, -62.88042]}
            rotation={[Math.PI / 2, 0, -1.5418]}
            scale={[0.04816, 0.04816, 0.04816]}
          >
            <mesh
              name="Fakultas_Kehutanan_FIX_BGT_BGT001"
              geometry={nodes.Fakultas_Kehutanan_FIX_BGT_BGT001.geometry}
              material={materials.Kehutanan_Body}
            />
            <mesh
              name="Fakultas_Kehutanan_FIX_BGT_BGT001_1"
              geometry={nodes.Fakultas_Kehutanan_FIX_BGT_BGT001_1.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              name="Fakultas_Kehutanan_FIX_BGT_BGT001_2"
              geometry={nodes.Fakultas_Kehutanan_FIX_BGT_BGT001_2.geometry}
              material={materials.Kehutanan_DarkGray}
            />
            <mesh
              name="Fakultas_Kehutanan_FIX_BGT_BGT001_3"
              geometry={nodes.Fakultas_Kehutanan_FIX_BGT_BGT001_3.geometry}
              material={materials.Kehutanan_LightBlue}
            />
            <mesh
              name="Fakultas_Kehutanan_FIX_BGT_BGT001_4"
              geometry={nodes.Fakultas_Kehutanan_FIX_BGT_BGT001_4.geometry}
              material={materials.Kehutanan_FireBrick}
            />
          </group>
          <group
            name="Fakultas_Matematika_dan_Ilmu_Pengetahuan_Alam"
            position={[-34.56371, 0.331, -38.56351]}
            rotation={[Math.PI / 2, 0, 0.01361]}
            scale={[0.60239, 0.60239, 0.60239]}
          >
            <mesh
              name="Fakultas_Matematika_dan_Ilmu_Pengetahuan_Alam001"
              geometry={
                nodes.Fakultas_Matematika_dan_Ilmu_Pengetahuan_Alam001.geometry
              }
              material={materials.MIPA_Body}
            />
            <mesh
              name="Fakultas_Matematika_dan_Ilmu_Pengetahuan_Alam001_1"
              geometry={
                nodes.Fakultas_Matematika_dan_Ilmu_Pengetahuan_Alam001_1
                  .geometry
              }
              material={materials.MIPA_Brown}
            />
            <mesh
              name="Fakultas_Matematika_dan_Ilmu_Pengetahuan_Alam001_2"
              geometry={
                nodes.Fakultas_Matematika_dan_Ilmu_Pengetahuan_Alam001_2
                  .geometry
              }
              material={materials.MIPA_LightBlue}
            />
            <mesh
              name="Fakultas_Matematika_dan_Ilmu_Pengetahuan_Alam001_3"
              geometry={
                nodes.Fakultas_Matematika_dan_Ilmu_Pengetahuan_Alam001_3
                  .geometry
              }
              material={materials.MIPA_DimGray}
            />
            <mesh
              name="Fakultas_Matematika_dan_Ilmu_Pengetahuan_Alam001_4"
              geometry={
                nodes.Fakultas_Matematika_dan_Ilmu_Pengetahuan_Alam001_4
                  .geometry
              }
              material={materials.MIPA_FireBrick}
            />
            <mesh
              name="Fakultas_Matematika_dan_Ilmu_Pengetahuan_Alam001_5"
              geometry={
                nodes.Fakultas_Matematika_dan_Ilmu_Pengetahuan_Alam001_5
                  .geometry
              }
              material={materials.MIPA_Black}
            />
          </group>
          <group
            name="Fakultas_Peternakan"
            position={[94.42848, 0.27794, -85.97483]}
            rotation={[Math.PI / 2, 0, 0.06903]}
            scale={[0.42715, 0.42715, 0.42715]}
          >
            <mesh
              name="Fakultas_Peternakan001"
              geometry={nodes.Fakultas_Peternakan001.geometry}
              material={materials.Peternakan_Body}
            />
            <mesh
              name="Fakultas_Peternakan001_1"
              geometry={nodes.Fakultas_Peternakan001_1.geometry}
              material={materials.Peternakan_Concrete}
            />
            <mesh
              name="Fakultas_Peternakan001_2"
              geometry={nodes.Fakultas_Peternakan001_2.geometry}
              material={materials.Peternakan_FireBrick}
            />
            <mesh
              name="Fakultas_Peternakan001_3"
              geometry={nodes.Fakultas_Peternakan001_3.geometry}
              material={materials.Peternakan_Black}
            />
            <mesh
              name="Fakultas_Peternakan001_4"
              geometry={nodes.Fakultas_Peternakan001_4.geometry}
              material={materials.Perternakan_Gray}
            />
          </group>
          <group
            name="Fakultas_Psikologi"
            position={[53.69445, -0.08437, 16.41666]}
            rotation={[Math.PI / 2, 0, -1.58618]}
            scale={[0.35121, 0.35121, 0.35121]}
          >
            <mesh
              name="Fakultas_Psikologi001"
              geometry={nodes.Fakultas_Psikologi001.geometry}
              material={materials.Psikologi_Body}
            />
            <mesh
              name="Fakultas_Psikologi001_1"
              geometry={nodes.Fakultas_Psikologi001_1.geometry}
              material={materials.Psikologi_DarkGray}
            />
            <mesh
              name="Fakultas_Psikologi001_2"
              geometry={nodes.Fakultas_Psikologi001_2.geometry}
              material={materials.Psikologi_FireBrick}
            />
            <mesh
              name="Fakultas_Psikologi001_3"
              geometry={nodes.Fakultas_Psikologi001_3.geometry}
              material={materials.Psikologi_Glass}
            />
          </group>
          <group
            name="Fakultas_Teknik"
            position={[-93.01392, -0.03238, -47.82277]}
            rotation={[Math.PI / 2, 0, 0.15022]}
            scale={[1.95794, 1.95794, 1.95794]}
          >
            <mesh
              name="Fakultas_Teknik001"
              geometry={nodes.Fakultas_Teknik001.geometry}
              material={materials.Teknik_Metal}
            />
            <mesh
              name="Fakultas_Teknik001_1"
              geometry={nodes.Fakultas_Teknik001_1.geometry}
              material={materials.Teknik_Keramik}
            />
            <mesh
              name="Fakultas_Teknik001_2"
              geometry={nodes.Fakultas_Teknik001_2.geometry}
              material={materials.Teknik_Gray}
            />
          </group>
          <group
            name="Fakultas_Teknologi_Pertanian"
            position={[20.0397, 0.35102, -31.1781]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.60752, 0.60752, 0.60752]}
          >
            <mesh
              name="Fakultas_Teknologi_Pertanian001"
              geometry={nodes.Fakultas_Teknologi_Pertanian001.geometry}
              material={materials.FTP_Black}
            />
            <mesh
              name="Fakultas_Teknologi_Pertanian001_1"
              geometry={nodes.Fakultas_Teknologi_Pertanian001_1.geometry}
              material={materials.FTP_Body}
            />
            <mesh
              name="Fakultas_Teknologi_Pertanian001_2"
              geometry={nodes.Fakultas_Teknologi_Pertanian001_2.geometry}
              material={materials.FTP_Accent}
            />
            <mesh
              name="Fakultas_Teknologi_Pertanian001_3"
              geometry={nodes.Fakultas_Teknologi_Pertanian001_3.geometry}
              material={materials.FTP_FireBrick}
            />
            <mesh
              name="Fakultas_Teknologi_Pertanian001_4"
              geometry={nodes.Fakultas_Teknologi_Pertanian001_4.geometry}
              material={materials.FTP_DarkGray}
            />
            <mesh
              name="Fakultas_Teknologi_Pertanian001_5"
              geometry={nodes.Fakultas_Teknologi_Pertanian001_5.geometry}
              material={materials.FTP_LightSteel}
            />
          </group>
          <group
            name="Gerbang_UGM"
            position={[-16.33356, 0.20853, 75.25538]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.04617, 0.04617, 0.04617]}
          >
            <mesh
              name="Gerbang_UGM002"
              geometry={nodes.Gerbang_UGM002.geometry}
              material={materials.Gerbang_BlackTop}
            />
            <mesh
              name="Gerbang_UGM002_1"
              geometry={nodes.Gerbang_UGM002_1.geometry}
              material={materials.Gerbang_Body}
            />
            <mesh
              name="Gerbang_UGM002_2"
              geometry={nodes.Gerbang_UGM002_2.geometry}
              material={materials.Gerbang_White}
            />
            <mesh
              name="Gerbang_UGM002_3"
              geometry={nodes.Gerbang_UGM002_3.geometry}
              material={materials.Gerbang_Allumunium}
            />
          </group>
          <group
            name="Grha_Sabha_Pramana"
            position={[2.41801, 0.01991, -9.86219]}
            rotation={[Math.PI / 2, 0, -3.12677]}
            scale={[0.01322, 0.01322, 0.01322]}
            onPointerOver={(e) => handleHover(e)}
            onPointerOut={(e) => clearHover(e)}
          >
            <mesh
              name="Grha_Sabha_Pramana001"
              geometry={nodes.Grha_Sabha_Pramana001.geometry}
              material={materials.GSP_Tulisan}
            />
            <mesh
              name="Grha_Sabha_Pramana001_1"
              geometry={nodes.Grha_Sabha_Pramana001_1.geometry}
              material={materials.GSP_Chocolate}
            />
            <mesh
              name="Grha_Sabha_Pramana001_2"
              geometry={nodes.Grha_Sabha_Pramana001_2.geometry}
              material={materials.GSP_Body}
            />
            <mesh
              name="Grha_Sabha_Pramana001_3"
              geometry={nodes.Grha_Sabha_Pramana001_3.geometry}
              material={materials.GSP_Silver}
            />
            <mesh
              name="Grha_Sabha_Pramana001_4"
              geometry={nodes.Grha_Sabha_Pramana001_4.geometry}
              material={materials.GSP_FireBrick}
            />
            <mesh
              name="Grha_Sabha_Pramana001_5"
              geometry={nodes.Grha_Sabha_Pramana001_5.geometry}
              material={materials.GSP_DarkGray}
            />
            <mesh
              name="Grha_Sabha_Pramana001_6"
              geometry={nodes.Grha_Sabha_Pramana001_6.geometry}
              material={materials.GSP_Brown}
            />
            <mesh
              name="Grha_Sabha_Pramana001_7"
              geometry={nodes.Grha_Sabha_Pramana001_7.geometry}
              material={materials.GSP_LimeGreen}
            />
            <mesh
              name="Grha_Sabha_Pramana001_8"
              geometry={nodes.Grha_Sabha_Pramana001_8.geometry}
              material={nodes.Grha_Sabha_Pramana001_8.material}
            />
            <mesh
              name="Grha_Sabha_Pramana001_9"
              geometry={nodes.Grha_Sabha_Pramana001_9.geometry}
              material={nodes.Grha_Sabha_Pramana001_9.material}
            />
          </group>
          <mesh
            name="Hospital"
            geometry={nodes.Hospital.geometry}
            material={materials.Hospital}
            position={[-31.01064, 0.18194, 28.5774]}
            rotation={[-Math.PI, 0.1409, -Math.PI]}
            scale={[2.0492, 2.0492, 2.0492]}
          />
          <mesh
            name="House1"
            geometry={nodes.House1.geometry}
            material={nodes.House1.material}
            position={[-8.38444, -0.03953, 37.14406]}
            rotation={[0, 1.55007, 0]}
            scale={[4.04535, 4.04535, 4.04535]}
          />
          <mesh
            name="House1001"
            geometry={nodes.House1001.geometry}
            material={nodes.House1001.material}
            position={[8.01467, -0.03953, 47.21003]}
            rotation={[0, -1.55761, 0]}
            scale={[3.89532, 3.89532, 3.89532]}
          />
          <mesh
            name="House2"
            geometry={nodes.House2.geometry}
            material={nodes.House2.material}
            position={[7.57315, -0.26931, 80.85517]}
            rotation={[0, -1.51119, 0]}
            scale={[3.75102, 3.75102, 3.75102]}
          />
          <mesh
            name="House3"
            geometry={nodes.House3.geometry}
            material={nodes.House3.material}
            position={[7.80515, -0.25995, 34.43641]}
            rotation={[0, 1.55397, 0]}
            scale={[3.91442, 3.91442, 3.91442]}
          />
          <mesh
            name="House4"
            geometry={nodes.House4.geometry}
            material={nodes.House4.material}
            position={[19.72392, -0.31212, 54.47191]}
            rotation={[0, -1.55688, 0]}
            scale={[3.84269, 3.84269, 3.84269]}
          />
          <mesh
            name="Lapangan_Pancasila"
            geometry={nodes.Lapangan_Pancasila.geometry}
            material={materials.Lapangan_Grass}
            position={[-6.72357, 0.12269, 11.04799]}
            scale={[2.35811, 2.35811, 2.35811]}
          />
          <group
            name="Masjid_Kampus"
            position={[51.32732, 0.07868, -8.98415]}
            rotation={[Math.PI / 2, 0, -1.03051]}
            scale={[0.2426, 0.2426, 0.2426]}
          >
            <mesh
              name="Masjid_Kampus001"
              geometry={nodes.Masjid_Kampus001.geometry}
              material={materials.Maskam_White}
            />
            <mesh
              name="Masjid_Kampus001_1"
              geometry={nodes.Masjid_Kampus001_1.geometry}
              material={materials.Maskam_FireBrick}
            />
            <mesh
              name="Masjid_Kampus001_2"
              geometry={nodes.Masjid_Kampus001_2.geometry}
              material={materials.Maskam_Silver}
            />
            <mesh
              name="Masjid_Kampus001_3"
              geometry={nodes.Masjid_Kampus001_3.geometry}
              material={materials.Maskam_Charcoal}
            />
            <mesh
              name="Masjid_Kampus001_4"
              geometry={nodes.Masjid_Kampus001_4.geometry}
              material={materials.Maskam_Cyan}
            />
            <mesh
              name="Masjid_Kampus001_5"
              geometry={nodes.Masjid_Kampus001_5.geometry}
              material={materials.Maskam_Yellow}
            />
            <mesh
              name="Masjid_Kampus001_6"
              geometry={nodes.Masjid_Kampus001_6.geometry}
              material={materials.Maskam_Tan}
            />
            <mesh
              name="Masjid_Kampus001_7"
              geometry={nodes.Masjid_Kampus001_7.geometry}
              material={materials.Maskam_Orange}
            />
            <mesh
              name="Masjid_Kampus001_8"
              geometry={nodes.Masjid_Kampus001_8.geometry}
              material={materials.Maskam_Maroon}
            />
            <mesh
              name="Masjid_Kampus001_9"
              geometry={nodes.Masjid_Kampus001_9.geometry}
              material={materials.Maskam_Coklat}
            />
          </group>
          <group
            name="Perpustakaan_Pusat"
            position={[-12.00918, 0.20852, -13.87015]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[0.00024, 0.00024, 0.00024]}
          >
            <mesh
              name="Perpustakaan_Pusat001"
              geometry={nodes.Perpustakaan_Pusat001.geometry}
              material={materials.Perpusat_Body}
            />
            <mesh
              name="Perpustakaan_Pusat001_1"
              geometry={nodes.Perpustakaan_Pusat001_1.geometry}
              material={materials.Perpusat_White}
            />
            <mesh
              name="Perpustakaan_Pusat001_2"
              geometry={nodes.Perpustakaan_Pusat001_2.geometry}
              material={materials.Perpusat_Turqoise}
            />
            <mesh
              name="Perpustakaan_Pusat001_3"
              geometry={nodes.Perpustakaan_Pusat001_3.geometry}
              material={materials.Perpusat_LightBlue}
            />
            <mesh
              name="Perpustakaan_Pusat001_4"
              geometry={nodes.Perpustakaan_Pusat001_4.geometry}
              material={materials.Perpusat_SteelBlue}
            />
          </group>
          <group name="Play" position={[-0.09465, 1.52805, 16.72853]}>
            <mesh
              name="Cube003"
              geometry={nodes.Cube003.geometry}
              material={materials.Play_Red}
            />
            <mesh
              name="Cube003_1"
              geometry={nodes.Cube003_1.geometry}
              material={materials.Play_White}
            />
          </group>
          <group
            name="Sekolah_Pascasarjana"
            position={[-84.67279, 0.9221, -72.02077]}
            rotation={[Math.PI / 2, 0, 0.12016]}
            scale={[0.00202, 0.00202, 0.00202]}
          >
            <mesh
              name="Sekolah_Pascasarjana001"
              geometry={nodes.Sekolah_Pascasarjana001.geometry}
              material={materials.Pasca_Wood}
            />
            <mesh
              name="Sekolah_Pascasarjana001_1"
              geometry={nodes.Sekolah_Pascasarjana001_1.geometry}
              material={materials.Pasca_Gray}
            />
            <mesh
              name="Sekolah_Pascasarjana001_2"
              geometry={nodes.Sekolah_Pascasarjana001_2.geometry}
              material={materials.Pasca_Body}
            />
            <mesh
              name="Sekolah_Pascasarjana001_3"
              geometry={nodes.Sekolah_Pascasarjana001_3.geometry}
              material={materials.Pasca_Red}
            />
            <mesh
              name="Sekolah_Pascasarjana001_4"
              geometry={nodes.Sekolah_Pascasarjana001_4.geometry}
              material={materials.Pasca_LightBlue}
            />
            <mesh
              name="Sekolah_Pascasarjana001_5"
              geometry={nodes.Sekolah_Pascasarjana001_5.geometry}
              material={materials.Pasca_Green}
            />
            <mesh
              name="Sekolah_Pascasarjana001_6"
              geometry={nodes.Sekolah_Pascasarjana001_6.geometry}
              material={materials.Pasca_DarkGray}
            />
          </group>
          <group
            name="Sekolah_Vokasi"
            position={[-27.97702, 0.24507, 84.90927]}
            rotation={[Math.PI / 2, 0, -1.43083]}
            scale={[2.42997, 2.42997, 2.42997]}
          >
            <mesh
              name="Sekolah_Vokasi002"
              geometry={nodes.Sekolah_Vokasi002.geometry}
              material={nodes.Sekolah_Vokasi002.material}
            />
            <mesh
              name="Sekolah_Vokasi002_1"
              geometry={nodes.Sekolah_Vokasi002_1.geometry}
              material={nodes.Sekolah_Vokasi002_1.material}
            />
            <mesh
              name="Sekolah_Vokasi002_2"
              geometry={nodes.Sekolah_Vokasi002_2.geometry}
              material={nodes.Sekolah_Vokasi002_2.material}
            />
            <mesh
              name="Sekolah_Vokasi002_3"
              geometry={nodes.Sekolah_Vokasi002_3.geometry}
              material={nodes.Sekolah_Vokasi002_3.material}
            />
            <mesh
              name="Sekolah_Vokasi002_4"
              geometry={nodes.Sekolah_Vokasi002_4.geometry}
              material={nodes.Sekolah_Vokasi002_4.material}
            />
            <mesh
              name="Sekolah_Vokasi002_5"
              geometry={nodes.Sekolah_Vokasi002_5.geometry}
              material={nodes.Sekolah_Vokasi002_5.material}
            />
            <mesh
              name="Sekolah_Vokasi002_6"
              geometry={nodes.Sekolah_Vokasi002_6.geometry}
              material={nodes.Sekolah_Vokasi002_6.material}
            />
            <mesh
              name="Sekolah_Vokasi002_7"
              geometry={nodes.Sekolah_Vokasi002_7.geometry}
              material={nodes.Sekolah_Vokasi002_7.material}
            />
            <mesh
              name="Sekolah_Vokasi002_8"
              geometry={nodes.Sekolah_Vokasi002_8.geometry}
              material={nodes.Sekolah_Vokasi002_8.material}
            />
            <mesh
              name="Sekolah_Vokasi002_9"
              geometry={nodes.Sekolah_Vokasi002_9.geometry}
              material={nodes.Sekolah_Vokasi002_9.material}
            />
            <mesh
              name="Sekolah_Vokasi002_10"
              geometry={nodes.Sekolah_Vokasi002_10.geometry}
              material={nodes.Sekolah_Vokasi002_10.material}
            />
            <mesh
              name="Sekolah_Vokasi002_11"
              geometry={nodes.Sekolah_Vokasi002_11.geometry}
              material={nodes.Sekolah_Vokasi002_11.material}
            />
            <mesh
              name="Sekolah_Vokasi002_12"
              geometry={nodes.Sekolah_Vokasi002_12.geometry}
              material={nodes.Sekolah_Vokasi002_12.material}
            />
            <mesh
              name="Sekolah_Vokasi002_13"
              geometry={nodes.Sekolah_Vokasi002_13.geometry}
              material={nodes.Sekolah_Vokasi002_13.material}
            />
          </group>
          <group
            name="Stadion_Pancasila"
            position={[107.02507, 0.22069, -43.66964]}
            rotation={[Math.PI / 2, 0, -2.0343]}
            scale={[0.00031, 0.00031, 0.00031]}
          >
            <mesh
              name="Stadion_Pancasila001"
              geometry={nodes.Stadion_Pancasila001.geometry}
              material={materials.Pancasila_Tribun}
            />
            <mesh
              name="Stadion_Pancasila001_1"
              geometry={nodes.Stadion_Pancasila001_1.geometry}
              material={materials.Pancasila_Rumput}
            />
            <mesh
              name="Stadion_Pancasila001_2"
              geometry={nodes.Stadion_Pancasila001_2.geometry}
              material={materials.Pancasila_Running}
            />
            <mesh
              name="Stadion_Pancasila001_3"
              geometry={nodes.Stadion_Pancasila001_3.geometry}
              material={materials.Pancsila_Fence}
            />
            <mesh
              name="Stadion_Pancasila001_4"
              geometry={nodes.Stadion_Pancasila001_4.geometry}
              material={materials.Pancasila_Garis}
            />
            <mesh
              name="Stadion_Pancasila001_5"
              geometry={nodes.Stadion_Pancasila001_5.geometry}
              material={materials.Pancasila_Roof}
            />
          </group>
          <mesh
            name="Rock_1_Cube001"
            geometry={nodes.Rock_1_Cube001.geometry}
            material={materials["Rock.001"]}
            position={[-1.29544, -0.3699, -97.38565]}
            rotation={[Math.PI / 2, 0, 1.93616]}
            scale={[25.48805, 25.48805, 25.48805]}
          />
          <mesh
            name="Rock_3_Cube001"
            geometry={nodes.Rock_3_Cube001.geometry}
            material={materials["Rock.002"]}
            position={[9.97311, 0.31285, -95.89817]}
            rotation={[Math.PI / 2, 0, 1.85086]}
            scale={[20.42432, 20.42432, 20.42432]}
          />
          <group
            name="Rock_Moss_3_Cube020"
            position={[-127.74235, 0.50285, -60.32824]}
            rotation={[Math.PI / 2, 0, -0.90541]}
            scale={[19.4751, 19.4751, 19.4751]}
          >
            <mesh
              name="Rock_Moss_3_Cube001"
              geometry={nodes.Rock_Moss_3_Cube001.geometry}
              material={materials.Rock}
            />
            <mesh
              name="Rock_Moss_3_Cube001_1"
              geometry={nodes.Rock_Moss_3_Cube001_1.geometry}
              material={materials["Moss_Green.001"]}
            />
          </group>
          <group
            name="Kelas_4"
            position={[103.86548, -0.05862, -31.47544]}
            rotation={[0, -1.46141, 0]}
            scale={[0.25592, 0.25592, 0.25592]}
          >
            <mesh
              name="Kelas_4_1"
              geometry={nodes.Kelas_4_1.geometry}
              material={materials["Kelas 4_Wall"]}
            />
            <mesh
              name="Kelas_4_2"
              geometry={nodes.Kelas_4_2.geometry}
              material={materials["Kelas 4_Roof"]}
            />
          </group>
          <group
            name="Kelas_4001"
            position={[-39.54369, -0.4356, -89.76921]}
            rotation={[-Math.PI, 1.47411, -Math.PI]}
            scale={[0.26502, 0.26502, 0.26502]}
          >
            <mesh
              name="Kelas_4001_1"
              geometry={nodes.Kelas_4001_1.geometry}
              material={materials["Kelas 4_Wall.001"]}
            />
            <mesh
              name="Kelas_4001_2"
              geometry={nodes.Kelas_4001_2.geometry}
              material={materials["Kelas 4_Roof.001"]}
            />
          </group>
          <group
            name="Kelas_4002"
            position={[-39.54369, -0.4356, -89.76921]}
            rotation={[-Math.PI, 1.47411, -Math.PI]}
            scale={[0.26502, 0.26502, 0.26502]}
          >
            <mesh
              name="element004"
              geometry={nodes.element004.geometry}
              material={materials["Kelas 4_Wall.002"]}
            />
            <mesh
              name="element004_1"
              geometry={nodes.element004_1.geometry}
              material={materials["Kelas 4_Roof.002"]}
            />
          </group>
          <group
            name="Kelas_4003"
            position={[76.70836, -0.32507, 60.3545]}
            rotation={[0, 0.16772, 0]}
            scale={[0.18832, 0.18832, 0.18832]}
          >
            <mesh
              name="element003"
              geometry={nodes.element003.geometry}
              material={materials["Kelas 4_Wall.003"]}
            />
            <mesh
              name="element003_1"
              geometry={nodes.element003_1.geometry}
              material={materials["Kelas 4_Roof.003"]}
            />
          </group>
          <group
            name="Kelas_4004"
            position={[-37.47063, 0.12381, -17.99341]}
            rotation={[0, 0.29579, 0]}
            scale={[0.14555, 0.14555, 0.14555]}
          >
            <mesh
              name="element002"
              geometry={nodes.element002.geometry}
              material={materials["Kelas 4_Wall.004"]}
            />
            <mesh
              name="element002_1"
              geometry={nodes.element002_1.geometry}
              material={materials["Kelas 4_Roof.004"]}
            />
          </group>
          <group
            name="Kelas_4005"
            position={[103.86548, -0.05862, -31.47544]}
            rotation={[0, -1.46141, 0]}
            scale={[0.25592, 0.25592, 0.25592]}
          >
            <mesh
              name="element001"
              geometry={nodes.element001.geometry}
              material={materials["Kelas 4_Wall.005"]}
            />
            <mesh
              name="element001_1"
              geometry={nodes.element001_1.geometry}
              material={materials["Kelas 4_Roof.005"]}
            />
          </group>
          <group
            name="BirchTree_1_Cube002"
            position={[-78.79922, -0.35643, -33.59641]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1.77166, 1.77166, 1.77166]}
          >
            <mesh
              name="BirchTree_1_Cube031"
              geometry={nodes.BirchTree_1_Cube031.geometry}
              material={materials["Birch_White.001"]}
            />
            <mesh
              name="BirchTree_1_Cube031_1"
              geometry={nodes.BirchTree_1_Cube031_1.geometry}
              material={materials["Birch_Green.001"]}
            />
            <mesh
              name="BirchTree_1_Cube031_2"
              geometry={nodes.BirchTree_1_Cube031_2.geometry}
              material={materials["Birch_DarkGreen.001"]}
            />
          </group>
          <group
            name="BirchTree_2_Cube001"
            position={[-71.4688, -0.05399, 75.20259]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1.78485, 1.78485, 1.78485]}
          >
            <mesh
              name="BirchTree_2_Cube005"
              geometry={nodes.BirchTree_2_Cube005.geometry}
              material={materials["Birch_White.002"]}
            />
            <mesh
              name="BirchTree_2_Cube005_1"
              geometry={nodes.BirchTree_2_Cube005_1.geometry}
              material={materials["Birch_Black.002"]}
            />
            <mesh
              name="BirchTree_2_Cube005_2"
              geometry={nodes.BirchTree_2_Cube005_2.geometry}
              material={materials["Birch_Green.002"]}
            />
            <mesh
              name="BirchTree_2_Cube005_3"
              geometry={nodes.BirchTree_2_Cube005_3.geometry}
              material={materials["Birch_DarkGreen.002"]}
            />
          </group>
          <group
            name="BirchTree_4_Cube001"
            position={[44.51228, -0.02338, 73.44132]}
            rotation={[Math.PI / 2, 0, -0.17229]}
            scale={[1.51165, 1.51165, 1.51165]}
          >
            <mesh
              name="BirchTree_4_Cube007"
              geometry={nodes.BirchTree_4_Cube007.geometry}
              material={materials["Birch_White.003"]}
            />
            <mesh
              name="BirchTree_4_Cube007_1"
              geometry={nodes.BirchTree_4_Cube007_1.geometry}
              material={materials["Birch_Green.003"]}
            />
            <mesh
              name="BirchTree_4_Cube007_2"
              geometry={nodes.BirchTree_4_Cube007_2.geometry}
              material={materials["Birch_DarkGreen.003"]}
            />
          </group>
          <group
            name="BirchTree_Dead_Snow_3"
            position={[18.94873, -23.1695, -30.31798]}
            rotation={[Math.PI / 2, 0, 0]}
          >
            <mesh
              name="BirchTree_Dead_Snow_3001"
              geometry={nodes.BirchTree_Dead_Snow_3001.geometry}
              material={materials.BirchDead_White}
            />
            <mesh
              name="BirchTree_Dead_Snow_3001_1"
              geometry={nodes.BirchTree_Dead_Snow_3001_1.geometry}
              material={materials.BirchDead_Black}
            />
            <mesh
              name="BirchTree_Dead_Snow_3001_2"
              geometry={nodes.BirchTree_Dead_Snow_3001_2.geometry}
              material={materials.Common_Dead_Snow}
            />
          </group>
          <group
            name="CommonTree_1_Cube001"
            position={[-33.66033, -0.01601, -127.35526]}
            rotation={[Math.PI / 2, 0, 1.73343]}
            scale={[1.68545, 1.68545, 1.68545]}
          >
            <mesh
              name="CommonTree_1_Cube004"
              geometry={nodes.CommonTree_1_Cube004.geometry}
              material={materials["Common_Wood.001"]}
            />
            <mesh
              name="CommonTree_1_Cube004_1"
              geometry={nodes.CommonTree_1_Cube004_1.geometry}
              material={materials["Common_Green.001"]}
            />
          </group>
          <group
            name="CommonTree_3_Cube001"
            position={[-60.26679, -0.01601, -111.96237]}
            rotation={[Math.PI / 2, 0, 0.74063]}
            scale={[2.62068, 2.62068, 2.62068]}
          >
            <mesh
              name="CommonTree_3_Cube003"
              geometry={nodes.CommonTree_3_Cube003.geometry}
              material={materials["Common_Wood.002"]}
            />
            <mesh
              name="CommonTree_3_Cube003_1"
              geometry={nodes.CommonTree_3_Cube003_1.geometry}
              material={materials["Common_Green.002"]}
            />
            <mesh
              name="CommonTree_3_Cube003_2"
              geometry={nodes.CommonTree_3_Cube003_2.geometry}
              material={materials["Common_DarkGreen.001"]}
            />
          </group>
          <group
            name="CommonTree_5_Cube014"
            position={[19.5181, -0.01601, -109.92073]}
            rotation={[Math.PI / 2, 0, 1.93007]}
            scale={[1.98773, 1.98773, 1.98773]}
          >
            <mesh
              name="CommonTree_5_Cube001"
              geometry={nodes.CommonTree_5_Cube001.geometry}
              material={materials["Common_Wood.003"]}
            />
            <mesh
              name="CommonTree_5_Cube001_1"
              geometry={nodes.CommonTree_5_Cube001_1.geometry}
              material={materials["Common_Green.003"]}
            />
            <mesh
              name="CommonTree_5_Cube001_2"
              geometry={nodes.CommonTree_5_Cube001_2.geometry}
              material={materials["Common_DarkGreen.002"]}
            />
          </group>
          <group
            name="CommonTree_Dead_Snow_5_Cube004"
            position={[-36.51102, -0.08053, -120.70761]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[2.92804, 2.92804, 2.92804]}
          >
            <mesh
              name="CommonTree_Dead_Snow_5_Cube001"
              geometry={nodes.CommonTree_Dead_Snow_5_Cube001.geometry}
              material={materials.Common_Dead_Wood}
            />
            <mesh
              name="CommonTree_Dead_Snow_5_Cube001_1"
              geometry={nodes.CommonTree_Dead_Snow_5_Cube001_1.geometry}
              material={materials["Common_Dead_Snow.001"]}
            />
          </group>
          <mesh
            name="Grass_Plane001"
            geometry={nodes.Grass_Plane001.geometry}
            material={materials.GrassPlane_Green}
            position={[34.86593, 0.0032, 93.44932]}
            rotation={[1.56253, -0.03552, -0.60829]}
            scale={[1.48001, 1.48001, 1.48001]}
          />
          <group
            name="PineTree_2_Cylinder001"
            position={[-120.66466, -0.28516, -2.02285]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1.61225, 1.61225, 1.61225]}
          >
            <mesh
              name="PineTree_2_Cylinder003"
              geometry={nodes.PineTree_2_Cylinder003.geometry}
              material={materials["Pine_Wood.001"]}
            />
            <mesh
              name="PineTree_2_Cylinder003_1"
              geometry={nodes.PineTree_2_Cylinder003_1.geometry}
              material={materials["Pine_Green.001"]}
            />
          </group>
          <group
            name="PineTree_3_Cylinder003"
            position={[-123.34909, -0.28516, -24.17017]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[2.02587, 2.02587, 2.02587]}
          >
            <mesh
              name="PineTree_3_Cylinder001"
              geometry={nodes.PineTree_3_Cylinder001.geometry}
              material={materials["Pine_Wood.002"]}
            />
            <mesh
              name="PineTree_3_Cylinder001_1"
              geometry={nodes.PineTree_3_Cylinder001_1.geometry}
              material={materials["Pine_Green.002"]}
            />
          </group>
          <group
            name="PineTree_4_Cylinder001"
            position={[-116.8884, -0.28516, -30.66232]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1.61225, 1.61225, 1.61225]}
          >
            <mesh
              name="PineTree_4_Cylinder015"
              geometry={nodes.PineTree_4_Cylinder015.geometry}
              material={materials["Pine_Wood.003"]}
            />
            <mesh
              name="PineTree_4_Cylinder015_1"
              geometry={nodes.PineTree_4_Cylinder015_1.geometry}
              material={materials["Pine_Green.003"]}
            />
          </group>
          <group
            name="PineTree_5_Cylinder001"
            position={[-15.36776, -0.47367, 13.9342]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[2.74684, 2.74684, 2.74684]}
          >
            <mesh
              name="PineTree_5_Cylinder024"
              geometry={nodes.PineTree_5_Cylinder024.geometry}
              material={materials["Pine_Wood.004"]}
            />
            <mesh
              name="PineTree_5_Cylinder024_1"
              geometry={nodes.PineTree_5_Cylinder024_1.geometry}
              material={materials["Pine_Green.004"]}
            />
          </group>
          <group
            name="TreeStump_Cylinder010"
            position={[-66.7493, -1.5805, 95.81677]}
            rotation={[Math.PI / 2, 0, -2.33694]}
            scale={[18.26317, 18.26317, 18.26317]}
          >
            <mesh
              name="TreeStump_Cylinder001"
              geometry={nodes.TreeStump_Cylinder001.geometry}
              material={materials.TreeStump_Wood}
            />
            <mesh
              name="TreeStump_Cylinder001_1"
              geometry={nodes.TreeStump_Cylinder001_1.geometry}
              material={materials.TreeStump_LightWood}
            />
            <mesh
              name="TreeStump_Cylinder001_2"
              geometry={nodes.TreeStump_Cylinder001_2.geometry}
              material={materials.TreeStump_Green}
            />
          </group>
          <group
            name="Willow_1_Cube001"
            position={[5.70605, -0.09584, 27.52172]}
            rotation={[Math.PI / 2, 0, 1.17002]}
            scale={[2.28481, 2.28481, 2.28481]}
          >
            <mesh
              name="Willow_1_Cube004"
              geometry={nodes.Willow_1_Cube004.geometry}
              material={materials["Willow_Wood.001"]}
            />
            <mesh
              name="Willow_1_Cube004_1"
              geometry={nodes.Willow_1_Cube004_1.geometry}
              material={materials["Willow_DarkGreen.001"]}
            />
          </group>
          <group
            name="Willow_4_Cube001"
            position={[-48.20575, -0.5419, 98.22061]}
            rotation={[Math.PI / 2, 0, -1.08446]}
            scale={[2.73588, 2.73588, 2.73588]}
          >
            <mesh
              name="Willow_4_Cube011"
              geometry={nodes.Willow_4_Cube011.geometry}
              material={materials["Willow_Wood.002"]}
            />
            <mesh
              name="Willow_4_Cube011_1"
              geometry={nodes.Willow_4_Cube011_1.geometry}
              material={materials["Willow_DarkGreen.002"]}
            />
          </group>
          <group
            name="WoodLog_Cylinder"
            position={[-90.15596, -3.48193, 68.70085]}
            rotation={[Math.PI / 2, 0, -0.62442]}
            scale={[18.03702, 18.03702, 18.03702]}
          >
            <mesh
              name="WoodLog_Cylinder001"
              geometry={nodes.WoodLog_Cylinder001.geometry}
              material={materials.WoodLog_Wood}
            />
            <mesh
              name="WoodLog_Cylinder001_1"
              geometry={nodes.WoodLog_Cylinder001_1.geometry}
              material={materials.WoodLog_Top}
            />
            <mesh
              name="WoodLog_Cylinder001_2"
              geometry={nodes.WoodLog_Cylinder001_2.geometry}
              material={materials.WoodLog_Bottom}
            />
          </group>
        </group>
      </group>
    </>
  );
}

useGLTF.preload("/model.glb");

function SpriteHover(props) {
  const spriteRef = useRef();
  useFrame(() => {
    if (props.object && spriteRef) {
      spriteRef.current.position.x = props.object.position.x / 100;
      spriteRef.current.position.z = props.object.position.z / 100 - 0.5;
    }
  });

  return (
    <group ref={spriteRef} visible={false}>
      <Html
        sprite
        transform
        position={[0, 0.2, 0]}
        style={{
          background: "white",
          fontSize: "6px",
          padding: "2px 5px",
          borderRadius: "25px",
          display: props.object ? "block" : "none",
        }}
      >
        {props.object ? props.object.name.replace(/\_/g, " ") : null}
      </Html>
    </group>
  );
}
